sudo: required

services:
  - docker

language: python

python:
  - '3.5'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - pip install -r requirements.txt

script: nosetests

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=georchestra/sdi-consistence-check
  - docker build -f Dockerfile -t $REPO:latest .
  - docker tag $REPO:latest $REPO:$COMMIT
  - docker push $REPO
