sudo: required

services:
  - docker

language: python

python:
  - '3.5'

env:
  global:
    - secure: "OW04Rw311ayBaqQDscsv+TSvHkCF/d6ZtwICeAsVQ8d0WA56JaQ4D8yAIId6JAf8ArwhkB7IyayqyXvyXwBO+C9Z6RD9MH94l5EKIfOvrBO0OcYJgbdjdBSq85+iWclqRkgSrnLuv5fm9dotSq9Bb474EeghLIF9lMKQoa0VbTssmF6pfa7Lu4WmHtXxDUCe5IQ27HmWawfFO6Rb3i9e2pSDPB9xHV+X2U4EUW3SVCspTCGpjGH/Sem7+8pzJ3JeQ8moYTocnYp7eyNtEH/1nrVfqW+frezFPySw0XyFxohemBO9amDfE6GrMMNBCKWpgc62drIpMjtvrNnDCrf95sk7krOrmJoNKl7jFP9WOT7cHGXT1XEHXhBTP/BjoGcD76P3QkwSW5W8iAR3fO9qz7q96CvUNyICcan2eXnvmNmfpxGwe/E7BEdWZq6FCXxyX/elr6kL1TNh02mFXdMbB8tMbwCWhHvyJLGSEtzjCIG850U102idU8xhv6yn8Q4I+qsYOltK6WkUPrAF8jg1A8uD8ZOsrBWGrCVSkIA7k2vjvpkaE0KQLwpS+ljKRN0JGUI+oWiZDtA4Nb+RGxg3ehBAjOKZnI1/YXM+8xtyv4hz+H5TDEVCpsRv3i+9Cx7Qpmf7aRSvHli5FEthbB2FYS6gGhPPkc2Ap87VcvdsPE0=" # DOCKER_EMAIL
    - secure: "HBqOVNcKw09jdXDyIJld0puEzszK2bF3vSwFRxCFWZNxGVYSwWr9+hyGplTgrK7PP1AjM4XP2rP6YuueI5GEOtd+LYQCY3I1EswAlVxOyjFDjthj8Lf52gamkqKacsbFkZx16odNGQjcu8qAJ2tDO9OEK8THQymUBxfi9Dl7/vuIRFZO+fqkdZprE9GLu4UFFSOKAf1TL3vU7DUOTiKZk5/e3FK8u3K2un9NJXP8BqsIz1uQ1q5QOsGqpwXBnalQioB98xxdTyq4Dip6RLOAUMcqvVXmEs6oteKaa9SXmVkmYxGtgTgcxz3wBLLUl1Or2R5+JJY6uxMM6b/yeH+2iiqbzPZkf4MKboUw8hqZW4t0ZqPgDwXTMTy1MLMG91rDe+Mj46biTlv5oglwcJISXyQQPkbziB0nq0uQczCtF7WrtBVqkAPazHA8ILct9o26H5SzEwbL1hxfgFyXMSl2mXkuJpC0VfJhC8g/RHmPDSBWJ1CFYERgZ/N9OAp6cWaZ612H4SM2rd20okfQ7bmJ7C3Hz9vxv0fpK/zoRUF1i/zoec4tEwdzEK231X3CqMm5ljVU1Xc/y0FtbMwL7ZknJ28mu+gdBqf/uPq6Nrk0DhxCYExPx7tP1+3qKr/o4t1BUqk6HQUxaKAoegalOZ1ulddlEMKDGAt0AqdQHfCXAHE=" # DOCKER_USER
    - secure: "B+jiBLP39sHHZ+3M4yifHCjMdlEtw10uFNMhJwbkFAxGcRRNMteNWpsPlX3GRFijLcdcRw1ljBF+HsCdGHHJL3XoYzBnJ8h3jk+hRs0XYCs/bPqhCWijzp7PJJB2HyDFvleUyiJOKUmtKk8DmpnnPGQbB9wHB7WJI3URga4EOpaZu863l1ZK5UEy1xZRVAVPzw0IgDGyqQShRLilVif4bI4dwtNMWOGVb1JHx52t2Q0BnU/L8AEl0M6VGDUyDoWPQ4P0eyjJhGuhMQKjiRkBx6at8YfBiXcnmGs/q7lVvjZIiFunDwpaQkxObbexRT4il3w0TTqukQ8kWUDtmcE51VyYPIwIO/lyheko34JWzh4Nq2ITpp4u/Cx6UZH9wudFIcFBx7JIqaMvcZ52Sa9RCTEpKr1UBzeKVawSX5oYRKeeqg+D/F3kk6h49ZG3bQ2ahvgcvSlQgJAaM8avxu4gEXLUHjJBF2SdvP0RD8AXr9pqSrtufs5MaHPhEBdO5DgfPu7frq5FeUA9Skk19a3bscqzUhl1C6r8CtvxuYlXiJ7Mr4cNp8A+hjT4uUz3ANxema12FaSfL1nBCHh8LoQqTPS1aVhrYyqK1xGTxbXRhJZjQ5qj9q0Owp7+q58dzLvYPiuCpavIu8UJodHaZjvJ0H/lP0jSiq5xT5K6ItARHNQ=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=georchestra/sdi-consistence-check
  - docker build -f Dockerfile -t $REPO:latest .
  - docker tag $REPO:latest $REPO:$COMMIT
  - docker push $REPO
